# Generated by Django 3.1.4 on 2020-12-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpage', '0002_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(to='fpage.Comment'),
        ),
    ]
