# Generated by Django 3.0.8 on 2020-12-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpage', '0006_auto_20201219_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, to='fpage.Comment'),
        ),
    ]
