# Generated by Django 3.0.8 on 2020-12-24 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpage', '0010_auto_20201224_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(default=datetime.time(5, 11, 13, 324629)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(default=datetime.time(5, 11, 13, 324629)),
        ),
    ]
